services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: wildinfo-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/wildinfo2.db:/app/backend/wildinfo2.db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: wildinfo-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
