sonar.projectKey=wilfinfo2
sonar.projectName=WildInfo
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/tailwind.css,**/__pycache__/**,**/*.db,**/animal/**,**/.venv/**,**/venv/**
sonar.python.version=3.12
